# THIS IS AN AUTOMATICALLY GENERATED FILE.
# DO NOT MODIFY BY HAND!!
#
# Generated by zcm-gen
#

begin
@static if VERSION < v"0.7.0-"
    @assert endswith(string(current_module()), "zcmtypes") "Only import this module through its parent"
else
    @assert endswith(string(@__MODULE__), "zcmtypes") "Only import this module through its parent"
end

import ZCM

export msg_t
mutable struct msg_t <: ZCM.AbstractZcmType

    # **********************
    # Members
    # **********************

    str                           ::String


    function msg_t()

        self = new()

        # **********************
        # Members
        # **********************

        self.str = ""

        return self
    end

end

const __msg_t_hash = Ref(Int64(0))
function ZCM._get_hash_recursive(::Type{msg_t}, parents::Array{String})
    if __msg_t_hash[] != 0; return __msg_t_hash[]; end
    if "msg_t" in parents; return 0; end
    hash::UInt64 = 0x4c9c80b2afc26e46
    hash = (hash << 1) + ((hash >>> 63) & 0x01)
    __msg_t_hash[] = reinterpret(Int64, hash)
    return __msg_t_hash[]
end

function ZCM.getHash(::Type{msg_t})
    return ZCM._get_hash_recursive(msg_t, Array{String,1}())
end

function ZCM._encode_one(msg::msg_t, buf)
    write(buf, hton(UInt32(length(msg.str) + 1)))
    write(buf, msg.str)
    write(buf, UInt8(0))
end

function ZCM.encode(msg::msg_t)
    buf = IOBuffer()
    write(buf, hton(ZCM.getHash(msg_t)))
    ZCM._encode_one(msg, buf)
    return ZCM.take!(buf);
end

function ZCM._decode_one(::Type{msg_t}, buf)
    msg = msg_t();
    msg.str = String(read(buf, ntoh(reinterpret(UInt32, read(buf, 4))[1])))[1:end-1]
    return msg
end

function ZCM.decode(::Type{msg_t}, data::Vector{UInt8})
    buf = IOBuffer(data)
    if ntoh(reinterpret(Int64, read(buf, 8))[1]) != ZCM.getHash(msg_t)
        throw("Decode error")
    end
    return ZCM._decode_one(msg_t, buf)
end

function ZCM.fieldnames(::Type{msg_t})
    return (
        :str,
    )
end

function ZCM.constfieldnames(::Type{msg_t})
    return (
    )
end

end # `begin` block
