/* ZCM type definition class file
 * This file was automatically generated by zcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package zcmtypes;
 
import java.io.*;
import java.util.*;
import zcm.zcm.*;
 
public final class msg_t implements zcm.zcm.ZCMEncodable
{
    public String str;
 
    public msg_t()
    {
    }
 
    public static final long ZCM_FINGERPRINT;
    public static final long ZCM_FINGERPRINT_BASE = 0x4c9c80b2afc26e46L;
 
    public static final boolean IS_LITTLE_ENDIAN = false;
    static {
        ZCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(zcmtypes.msg_t.class))
            return 0L;
 
        classes.add(zcmtypes.msg_t.class);
        long hash = ZCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>>63)&1);
    }
 
    public void encode(ZCMDataOutputStream outs) throws IOException
    {
        outs.writeLong(ZCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(ZCMDataOutputStream outs) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[this.str.length()]; this.str.getChars(0, this.str.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; ++_i) outs.write(__strbuf[_i]); outs.writeByte(0);
 
    }
 
    public msg_t(byte[] data) throws IOException
    {
        this(new ZCMDataInputStream(data));
    }
 
    public msg_t(ZCMDataInputStream ins) throws IOException
    {
        if (ins.readLong() != ZCM_FINGERPRINT)
            throw new IOException("ZCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static zcmtypes.msg_t _decodeRecursiveFactory(ZCMDataInputStream ins) throws IOException
    {
        zcmtypes.msg_t o = new zcmtypes.msg_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(ZCMDataInputStream ins) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; ++_i) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.str = new String(__strbuf);
 
    }
 
    public zcmtypes.msg_t copy()
    {
        zcmtypes.msg_t outobj = new zcmtypes.msg_t();
        outobj.str = this.str;
 
        return outobj;
    }
 
}

